apiVersion: v1
data:
  loadBalancerScheme: {{ .Values.alb.scheme }}
kind: ConfigMap
metadata:
  labels:
    kustomize.component: istio-ingress
  name: istio-ingress-parameters
  namespace: istio-system
