bases:
- ../../base
patchesStrategicMerge:
- ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: istio-ingress-parameters
  behavior: merge
  envs:
  - params.env
vars:
- name: certArn
  objref:
    kind: ConfigMap
    name: istio-ingress-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.certArn
namespace: istio-system
