apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- auth-service.yaml
- auth-deployment.yaml
- virtual-service.yaml
configMapGenerator:
- name: authservice-config
  env: params.env