apiVersion: v1
data:
  agent: "{\n    \"image\" : \"kfserving/agent:v0.6.1\",\n    \"memoryRequest\": \"\
    100Mi\",\n    \"memoryLimit\": \"1Gi\",\n    \"cpuRequest\": \"100m\",\n    \"\
    cpuLimit\": \"1\"\n}"
  batcher: "{\n    \"image\" : \"kfserving/agent:v0.6.1\",\n    \"memoryRequest\"\
    : \"1Gi\",\n    \"memoryLimit\": \"1Gi\",\n    \"cpuRequest\": \"1\",\n    \"\
    cpuLimit\": \"1\"\n}"
  credentials: "{\n   \"gcs\": {\n       \"gcsCredentialFileName\": \"gcloud-application-credentials.json\"\
    \n   },\n   \"s3\": {\n       \"s3AccessKeyIDName\": \"AWS_ACCESS_KEY_ID\",\n\
    \       \"s3SecretAccessKeyName\": \"AWS_SECRET_ACCESS_KEY\"\n   }\n}"
  explainers: "{\n    \"alibi\": {\n        \"image\" : \"kfserving/alibi-explainer\"\
    ,\n        \"defaultImageVersion\": \"v0.6.1\"\n    },\n    \"aix\": {\n     \
    \   \"image\" : \"kfserving/aix-explainer\",\n        \"defaultImageVersion\"\
    : \"v0.6.1\"\n    },\n    \"art\": {\n        \"image\" : \"kfserving/art-explainer\"\
    ,\n        \"defaultImageVersion\": \"v0.6.1\"\n    }\n}"
  ingress: "{\n    \"ingressGateway\" : \"kubeflow/kubeflow-gateway\",\n    \"ingressService\"\
    \ : \"istio-ingressgateway.istio-system.svc.cluster.local\",\n    \"localGateway\"\
    \ : \"knative-serving/knative-local-gateway\",\n    \"localGatewayService\" :\
    \ \"knative-local-gateway.istio-system.svc.cluster.local\"\n}"
  logger: "{\n    \"image\" : \"kfserving/agent:v0.6.1\",\n    \"memoryRequest\":\
    \ \"100Mi\",\n    \"memoryLimit\": \"1Gi\",\n    \"cpuRequest\": \"100m\",\n \
    \   \"cpuLimit\": \"1\",\n    \"defaultUrl\": \"http://default-broker\"\n}"
  predictors: "{\n    \"tensorflow\": {\n        \"image\": \"tensorflow/serving\"\
    ,\n        \"defaultImageVersion\": \"1.14.0\",\n        \"defaultGpuImageVersion\"\
    : \"1.14.0-gpu\",\n        \"defaultTimeout\": \"60\",\n        \"supportedFrameworks\"\
    : [\n          \"tensorflow\"\n        ],\n        \"multiModelServer\": false\n\
    \    },\n    \"onnx\": {\n        \"image\": \"mcr.microsoft.com/onnxruntime/server\"\
    ,\n        \"defaultImageVersion\": \"v1.0.0\",\n        \"supportedFrameworks\"\
    : [\n          \"onnx\"\n        ],\n        \"multiModelServer\": false\n   \
    \ },\n    \"sklearn\": {\n      \"v1\": {\n        \"image\": \"kfserving/sklearnserver\"\
    ,\n        \"defaultImageVersion\": \"v0.6.1\",\n        \"supportedFrameworks\"\
    : [\n          \"sklearn\"\n        ],\n        \"multiModelServer\": true\n \
    \     },\n      \"v2\": {\n        \"image\": \"docker.io/seldonio/mlserver\"\
    ,\n        \"defaultImageVersion\": \"0.2.1\",\n        \"supportedFrameworks\"\
    : [\n          \"sklearn\"\n        ],\n        \"multiModelServer\": false\n\
    \      }\n    },\n    \"xgboost\": {\n      \"v1\": {\n        \"image\": \"kfserving/xgbserver\"\
    ,\n        \"defaultImageVersion\": \"v0.6.1\",\n        \"supportedFrameworks\"\
    : [\n          \"xgboost\"\n        ],\n        \"multiModelServer\": true\n \
    \     },\n      \"v2\": {\n        \"image\": \"docker.io/seldonio/mlserver\"\
    ,\n        \"defaultImageVersion\": \"0.2.1\",\n        \"supportedFrameworks\"\
    : [\n          \"xgboost\"\n        ],\n        \"multiModelServer\": false\n\
    \      }\n    },\n    \"pytorch\": {\n      \"v1\" : {\n        \"image\": \"\
    kfserving/pytorchserver\",\n        \"defaultImageVersion\": \"v0.6.1\",\n   \
    \     \"defaultGpuImageVersion\": \"v0.6.1-gpu\",\n        \"supportedFrameworks\"\
    : [\n          \"pytorch\"\n        ],\n        \"multiModelServer\": false\n\
    \      },\n      \"v2\" : {\n        \"image\": \"pytorch/torchserve-kfs\",\n\
    \        \"defaultImageVersion\": \"0.4.0\",\n        \"defaultGpuImageVersion\"\
    : \"0.4.0-gpu\",\n        \"supportedFrameworks\": [\n          \"pytorch\"\n\
    \        ],\n        \"multiModelServer\": false\n      }\n    },\n    \"triton\"\
    : {\n        \"image\": \"nvcr.io/nvidia/tritonserver\",\n        \"defaultImageVersion\"\
    : \"20.08-py3\",\n        \"supportedFrameworks\": [\n          \"tensorrt\",\n\
    \          \"tensorflow\",\n          \"onnx\",\n          \"pytorch\",\n    \
    \      \"caffe2\"\n        ],\n        \"multiModelServer\": true\n    },\n  \
    \  \"pmml\": {\n        \"image\": \"kfserving/pmmlserver\",\n        \"defaultImageVersion\"\
    : \"v0.6.1\",\n        \"supportedFrameworks\": [\n          \"pmml\"\n      \
    \  ],\n        \"multiModelServer\": false\n    },\n    \"lightgbm\": {\n    \
    \    \"image\": \"kfserving/lgbserver\",\n        \"defaultImageVersion\": \"\
    v0.6.1\",\n        \"supportedFrameworks\": [\n          \"lightgbm\"\n      \
    \  ],\n        \"multiModelServer\": false\n    },\n    \"paddle\": {\n      \
    \  \"image\": \"kfserving/paddleserver\",\n        \"defaultImageVersion\": \"\
    v0.6.1\",\n        \"supportedFrameworks\": [\n          \"paddle\"\n        ],\n\
    \        \"multiModelServer\": false\n    }\n}"
  storageInitializer: "{\n    \"image\" : \"kfserving/storage-initializer:v0.6.1\"\
    ,\n    \"memoryRequest\": \"100Mi\",\n    \"memoryLimit\": \"1Gi\",\n    \"cpuRequest\"\
    : \"100m\",\n    \"cpuLimit\": \"1\"\n}"
  transformers: '{

    }'
kind: ConfigMap
metadata:
  labels:
    app: kfserving
    app.kubernetes.io/name: kfserving
  name: inferenceservice-config
  namespace: kubeflow
