apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-xgbserver
spec:
  containers:
  - args:
    - --model_name={{`{{.Name}}`}}
    - --model_dir=/mnt/models
    - --http_port=8080
    - --nthread=1
    image: kserve/xgbserver:v0.8.0
    name: kserve-container
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: '1'
        memory: 2Gi
  supportedModelFormats:
  - autoSelect: true
    name: xgboost
    version: '1'
