apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Kubeflow namespace
- ../../../../common/kubeflow-namespace/base
# Kubeflow Roles
- ../../../../common/kubeflow-roles/base
# Cert-Manager
- ../../../../common/cert-manager/cert-manager/base
- ../../../../common/cert-manager/kubeflow-issuer/base
# Istio
- ../../../../common/istio-1-9/istio-crds/base
- ../../../../common/istio-1-9/istio-namespace/base
- ../../../../common/istio-1-9/istio-install/base
# KNative
- ../../../../common/knative/knative-serving/base
- ../../../../common/knative/knative-eventing/base
- ../../../../common/istio-1-9/cluster-local-gateway/base
# Kubeflow Istio Resources
- ../../../../common/istio-1-9/kubeflow-istio-resources/base

# KFServing
- ../../../../apps/kfserving/upstream/overlays/kubeflow
# Central Dashboard
- ../../../../apps/centraldashboard/upstream/overlays/istio
# Notebooks
- ../../../../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
- ../../../../apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Admission Webhook
- ../../../../apps/admission-webhook/upstream/overlays/cert-manager
# Profiles + KFAM
- ../../../../apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ../../../../apps/volumes-web-app/upstream/overlays/istio
# Tensorboard
- ../../../../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
- ../../../../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# TFJob Operator
- ../../../../apps/tf-training/upstream/overlays/kubeflow
# Pytorch Operator
- ../../../../apps/pytorch-job/upstream/overlays/kubeflow
# MPI Operator
- ../../../../apps/mpi-job/upstream/overlays/kubeflow
# MXNet Operator
- ../../../../apps/mxnet-job/upstream/overlays/kubeflow
# XGBoost Operator
- ../../../../apps/xgboost-job/upstream/overlays/kubeflow

# Configured for AWS Cognito

# Ingress
- ../../istio-ingress/overlays/cognito
# ALB controller
- ../../aws-alb-ingress-controller/base
# Envoy filter
- ../../aws-istio-envoy-filter/base
# AWS Telemetry - This is an optional component. See usage tracking documentation for more information
- ../../aws-telemetry

# Configured for AWS RDS and AWS S3

# AWS Secret Manager
- ../../../../distributions/aws/aws-secrets-manager/base
# Kubeflow Pipelines
- ../../../../apps/pipeline/upstream/env/aws
# Katib
- ../../../../apps/katib/upstream/installs/katib-external-db-with-kubeflow