apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../../../aws/aws-alb-ingress-controller/base_v3
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: aws-alb-ingress-controller-config
  envs:
  - ../../../../aws/aws-alb-ingress-controller/base/params.env
vars:
- name: clusterName
  objref:
    kind: ConfigMap
    name: aws-alb-ingress-controller-config
    apiVersion: v1
  fieldref:
    fieldpath: data.clusterName