apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-dynamic
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-dynamic
  resources:
    requests:
      storage: 5Gi