apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
  - ../../aws-secrets-manager/base
resources:
  - secret-provider.yaml
patchesStrategicMerge:
  - deployment_patch.yaml
