apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- deployment.yaml
- service-account.yaml
commonLabels:
  app: aws-alb-ingress-controller
  kustomize.component: aws-alb-ingress-controller
generatorOptions:
  disableNameSuffixHash: true
images:
- name: docker.io/amazon/aws-alb-ingress-controller
  newName: docker.io/amazon/aws-alb-ingress-controller
  newTag: v1.1.5
configMapGenerator:
- name: aws-alb-ingress-controller-config
  envs:
  - params.env
vars:
- name: clusterName
  objref:
    kind: ConfigMap
    name: aws-alb-ingress-controller-config
    apiVersion: v1
  fieldref:
    fieldpath: data.clusterName
patchesStrategicMerge:
- deployment_patch.yaml
