apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    kfctl.kubeflow.io/force-delete: "false"
  # clusterName: ${CLUSTER_NAME}.${CLUSTER_REGION}.eksctl.io 
  creationTimestamp: null
  # name: ${CLUSTER_NAME}
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/kubeflow-namespace/base
    name: kubeflow-namespace
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/kubeflow-roles/base
    name: kubeflow-roles
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/aws/application/istio-1-9-1-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/cert-manager/cert-manager/base
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/cert-manager/kubeflow-issuer/base
    name: cert-manager-kubeflow-self-signed
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/dex/overlays/istio
    name: dex
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/oidc-authservice/base
    name: oidc-authservice
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/knative/knative-serving/base
    name: knative-serving
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/knative/knative-eventing/base
    name: knative-serving
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/istio-1-9/kubeflow-istio-resources/base
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/pipeline/upstream/env/platform-agnostic
    name: kubeflow-pipelines
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/kfserving/upstream/overlays/kubeflow
    name: kfserving
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/katib/upstream/installs/katib-with-kubeflow
    name: katib
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/centraldashboard/upstream/overlays/istio
    name: central-dashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/aws/application/notebooks
    name: notebooks
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/profiles/upstream/overlays/kubeflow
    name: profiles
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/volumes-web-app/upstream/overlays/istio
    name: volumes-web-app
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/aws/application/tensorboard
    name: tensorboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/tf-training/upstream/overlays/kubeflow
    name: tfjob-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/pytorch-job/upstream/overlays/kubeflow
    name: pytorch-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/mpi-job/upstream/overlays/kubeflow
    name: mpi-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/mxnet-job/upstream/overlays/kubeflow
    name: mxnet-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: apps/xgboost-job/upstream/overlays/kubeflow
    name: xgboost-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/user-namespace/base
    name: user-namespace
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.3.0.tar.gz
  version: v1.3.0