apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../rds-s3/base
resources:
  # Configured for AWS S3

  # AWS Secret Manager
  - ../../../awsconfigs/common/aws-secrets-manager/s3
  # Kubeflow Pipelines
  - ../../../awsconfigs/apps/pipeline/s3

  # Katib
  - ../../../upstream/apps/katib/upstream/installs/katib-with-kubeflow
