apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    eventing.knative.dev/release: v0.22.1
    kustomize.component: knative
  name: eventing-webhook-certs
  namespace: knative-eventing
