aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      duck.knative.dev/addressable: 'true'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.2.4
    eventing.knative.dev/release: v1.2.4
    kustomize.component: knative
  name: addressable-resolver
rules: []
