$patch: delete
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline
  namespace: kubeflow
eksctl create addon --name aws-ebs-csi-driver --cluster tests --service-account-role-arn arn:aws:iam::024825446905:role/AmazonEKS_EBS_CSI_DriverRole --force