apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
- ../../pipeline/s3/
configMapGenerator:
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
- disable-default-secret.yaml