apiVersion: v1
kind: Service
metadata:
  labels:
    app: kfserving
    app.kubernetes.io/component: kfserving-models-web-app
    app.kubernetes.io/name: kfserving
    kustomize.component: kfserving-models-web-app
  name: kfserving-models-web-app
  namespace: kubeflow
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: kfserving
    app.kubernetes.io/component: kfserving-models-web-app
    app.kubernetes.io/name: kfserving
    kustomize.component: kfserving-models-web-app
  type: ClusterIP
