kind: Pod
apiVersion: v1
metadata:
  name: kubeflow-secrets-pod
  namespace: kubeflow
spec:
  serviceAccountName: kubeflow-secrets-manager-sa
  containers:
  - name: secrets
    image: nginx:1.14.2
    volumeMounts:
    - name: kubeflow-secrets
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: kubeflow-secrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws-secrets"