kind: Pod
apiVersion: v1
metadata:
  name: kubeflow-secrets-pod
  namespace: kubeflow
spec:
  serviceAccountName: kubeflow-secrets-manager-sa
  containers:
  - name: secrets
    image: public.ecr.aws/xray/aws-xray-daemon:latest
    volumeMounts:
    - name: rds-secret
      mountPath: "/mnt/rds-store"
      readOnly: true
    - name: s3-secret
      mountPath: "/mnt/aws-store"
      readOnly: true
  volumes:
    - name: rds-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws-secrets"
    - name: s3-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws-secrets"