apiVersion: v1
data:
  default-br-config: "clusterDefault:\n  brokerClass: MTChannelBasedBroker\n  apiVersion:\
    \ v1\n  kind: ConfigMap\n  name: config-br-default-channel\n  namespace: knative-eventing\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    eventing.knative.dev/release: v0.22.1
    kustomize.component: knative
  name: config-br-defaults
  namespace: knative-eventing
