apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-controller-deployment
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: ENABLE_CULLING
          valueFrom:
            configMapKeyRef:
              key: enableCulling
              name: config
        - name: CULL_IDLE_TIME
          valueFrom:
            configMapKeyRef:
              key: cullIdleTime
              name: config
        - name: IDLENESS_CHECK_PERIOD
          valueFrom:
            configMapKeyRef:
              key: idlenessCheckPeriod
              name: config
