apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
- ../../../upstream/apps/jupyter/notebook-controller/upstream/overlays/kubeflow
configMapGenerator:
- name: config
  behavior: merge
  env: params.env

