apiVersion: v1
data:
  ISTIO_GATEWAY: kubeflow/kubeflow-gateway
  USE_ISTIO: 'true'
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
  name: notebook-controller-config-kkt88f2bhb
  namespace: kubeflow
