FROM public.ecr.aws/ubuntu/ubuntu:18.04

RUN apt-get update && apt-get install -y curl \
    wget \
    git \
    python3.8 \
    python3-pip \
    python3.8-dev \
    vim \
    sudo \
    jq \
    unzip

# Install awscli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
 && unzip -qq awscliv2.zip \
 && ./aws/install

# Install kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.8/bin/linux/amd64/kubectl \
 && chmod +x ./kubectl \
 && cp ./kubectl /bin

# Install eksctl
RUN curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp && mv /tmp/eksctl /bin

# Install kustomize 
RUN curl --silent --location "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.1/kustomize_v5.0.1_linux_amd64.tar.gz" | tar xz -C /tmp \
 && chmod +x /tmp/kustomize \
 && mv /tmp/kustomize /bin/kustomize



#Install helm
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
 && chmod +x get_helm.sh \
 && ./get_helm.sh

RUN wget https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64.tar.gz -O - | tar xz \
 && mv yq_linux_amd64 /usr/bin/yq \
 && rm install-man-page.sh \
 && rm yq.1 \
 && yq --version

ENV REPO_PATH=/kubeflow-manifests
COPY ./tests/e2e/requirements.txt requirements.txt

RUN ln -s /usr/bin/python3.8 /usr/bin/python \
 && python -m pip install --upgrade pip

RUN python -m pip install -r requirements.txt

WORKDIR /$REPO_PATH
CMD ["./tests/canary/scripts/run_test.sh"]
