---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-sagemaker-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - apps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - dataqualityjobdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - dataqualityjobdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - domains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - domains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - endpointconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - endpointconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - endpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - featuregroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - featuregroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - hyperparametertuningjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - hyperparametertuningjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelbiasjobdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelbiasjobdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelexplainabilityjobdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelexplainabilityjobdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelpackagegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelpackagegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelpackages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelqualityjobdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelqualityjobdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - monitoringschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - monitoringschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - notebookinstancelifecycleconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - notebookinstancelifecycleconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - notebookinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - notebookinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - pipelineexecutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - pipelineexecutions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - processingjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - processingjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - trainingjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - trainingjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - transformjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - transformjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - userprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - userprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports/status
  verbs:
  - get
  - patch
  - update
