apiVersion: v1
data:
  _example: '################################

    #                              #

    #    EXAMPLE CONFIGURATION     #

    #                              #

    ################################

    # This block is not actually functional configuration,

    # but serves to illustrate the available configuration

    # options and document them in a way that is accessible

    # to users that `kubectl edit` this config map.

    #

    # These sample configuration options may be copied out of

    # this example block and unindented to be in the data block

    # to actually change the configuration.

    #

    # This may be "zipkin" or "none". the default is "none"

    backend: "none"


    # URL to zipkin collector where traces are sent.

    # This must be specified when backend is "zipkin"

    zipkin-endpoint: "http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans"


    # Enable zipkin debug mode. This allows all spans to be sent to the server

    # bypassing sampling.

    debug: "false"


    # Percentage (0-1) of requests to trace

    sample-rate: "0.1"

    '
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: 0492ceb0
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.8.1
    eventing.knative.dev/release: v1.8.1
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
    kustomize.component: knative
  name: config-tracing
  namespace: knative-eventing
