apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - csidriver.yaml
  - node-daemonset.yaml
  - node-serviceaccount.yaml
  - controller-deployment.yaml
  - controller-serviceaccount.yaml
