apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: controller
          env:
          - name: CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: aws-load-balancer-controller-config
                key: clusterName
