apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
# Manifests downloaded from:
# https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.4.1/v2_4_1_full.yaml
# change from original manifest is in Deployment named aws-load-balancer-controller for controller container args: --cluster-name=$(CLUSTER_NAME)
- load_balancer_controller.yaml
commonLabels:
  kustomize.component: aws-load-balancer-controller
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: aws-load-balancer-controller-config
  envs:
  - params.env
vars:
- name: clusterName
  objref:
    kind: ConfigMap
    name: aws-load-balancer-controller-config
    apiVersion: v1
  fieldref:
    fieldpath: data.clusterName
patchesStrategicMerge:
- deployment_patch.yaml
