apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../upstream/apps/jupyter/jupyter-web-app/upstream/overlays/istio
configMapGenerator:
- name: config
  behavior: merge
  files:
  - configs/spawner_ui_config.yaml