apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
bases:
- ../../../upstream/common/dex/overlays/istio

patchesStrategicMerge:
- patches/service.yaml
- patches/disable-nodeport.yaml