notebook-controller:
  params:
    template_paths: 
      - tools/helmify/template/notebook-controller/params.env
    target_paths:
      - awsconfigs/apps/notebook-controller/params.env
  values:
    template_paths:
      - tools/helmify/template/notebook-controller/values.yaml
    target_paths:
      - charts/apps/notebook-controller/values.yaml


kubeflow-pipelines:
  params:
    template_paths: 
      - tools/helmify/template/kubeflow-pipelines/params/s3/params.env
      - tools/helmify/template/kubeflow-pipelines/params/rds/params.env
    target_paths:
      - awsconfigs/apps/pipeline/s3/params.env
      - awsconfigs/apps/pipeline/rds/params.env
  values:
    template_paths:
      - tools/helmify/template/kubeflow-pipelines/values/rds-s3/values.yaml
      - tools/helmify/template/kubeflow-pipelines/values/s3-only/values.yaml
      - tools/helmify/template/kubeflow-pipelines/values/rds-only/values.yaml
    target_paths:
      - charts/apps/kubeflow-pipelines/rds-s3/values.yaml
      - charts/apps/kubeflow-pipelines/s3-only/values.yaml
      - charts/apps/kubeflow-pipelines/rds-only/values.yaml
    
    
aws-authservice:
  params:
    template_paths: 
      - tools/helmify/template/aws-authservice/params.env
    target_paths:
      - awsconfigs/common/aws-authservice/base/params.env
  values:
    template_paths:
      - tools/helmify/template/aws-authservice/values.yaml
    target_paths:
      - charts/common/aws-authservice/values.yaml



ingress:
  params:
    template_paths:
      - tools/helmify/template/ingress/params/overlays/cognito/params.env
      - tools/helmify/template/ingress/params/base/params.env
    target_paths:
      - awsconfigs/common/istio-ingress/overlays/cognito/params.env
      - awsconfigs/common/istio-ingress/base/params.env
  values:
    template_paths:
      - tools/helmify/template/ingress/values/cognito/values.yaml
    target_paths:
      - charts/common/ingress/cognito/values.yaml


aws-secrets-manager:
  params:
    template_paths:
      - tools/helmify/template/aws-secrets-manager/params/rds/secret-provider.yaml
      - tools/helmify/template/aws-secrets-manager/params/s3/secret-provider.yaml
    target_paths:
      - awsconfigs/common/aws-secrets-manager/rds/secret-provider.yaml
      - awsconfigs/common/aws-secrets-manager/s3/secret-provider.yaml
  values:
    template_paths:
      - tools/helmify/template/aws-secrets-manager/values/rds-only/values.yaml
      - tools/helmify/template/aws-secrets-manager/values/rds-s3/values.yaml
      - tools/helmify/template/aws-secrets-manager/values/s3-only/values.yaml
    target_paths:
      - charts/common/aws-secrets-manager/rds-only/values.yaml
      - charts/common/aws-secrets-manager/rds-s3/values.yaml
      - charts/common/aws-secrets-manager/s3-only/values.yaml