apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: rds-secret
  namespace: kubeflow
spec:
  parameters:
    objects: |
      - jmesPath:
        - objectAlias: user
          path: username
        - objectAlias: pass
          path: password
        - objectAlias: host
          path: host
        - objectAlias: database
          path: database
        - objectAlias: port
          path: port
        objectName: {{ .Values.rds.secretName }}
        objectType: secretsmanager
  provider: aws
  secretObjects:
  - data:
    - key: username
      objectName: user
    - key: password
      objectName: pass
    - key: host
      objectName: host
    - key: database
      objectName: database
    - key: port
      objectName: port
    secretName: mysql-secret
    type: Opaque