apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
  - ./base
resources:
  - ./rds/secret-provider.yaml
  - ./s3/secret-provider.yaml
patchesStrategicMerge:
  - ./rds/deployment_patch.yaml
  - ./s3/deployment_patch.yaml
