$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: kubeflow
---
$patch: delete
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: kubeflow
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: kubeflow
