apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
- ../base
configMapGenerator:
- name: pipeline-install-config
  env: params.env
  behavior: merge
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config
- name: ml-pipeline-ui-configmap
  behavior: replace
  files:
  - viewer-pod-template.json
- name: kubeflow-pipelines-profile-controller-code
  behavior: replace
  files:
  - sync.py
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
- disable-minio-server-resources.yaml
- deployment_patch.yaml
- disable-default-secret.yaml
- service-account.yaml
- aws-configuration-patch.yaml
# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines
vars:
- name: kfp-artifact-storage-endpoint
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.minioServiceHost
