apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: rds-secret
  namespace: kubeflow
spec:
  parameters:
    objects: "- jmesPath:\n  - objectAlias: user\n    path: username\n  - objectAlias:\
      \ pass\n    path: password\n  - objectAlias: host\n    path: host\n  - objectAlias:\
      \ database\n    path: database\n  - objectAlias: port\n    path: port\n  objectName:\
      \ {{ .Values.rds.secretName }}\n  objectType: secretsmanager\n"
  provider: aws
  secretObjects:
  - data:
    - key: username
      objectName: user
    - key: password
      objectName: pass
    - key: host
      objectName: host
    - key: database
      objectName: database
    - key: port
      objectName: port
    secretName: mysql-secret
    type: Opaque
