apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"{{ .Values.cognitoUserpool.ARN
      }}","UserPoolClientId":"{{ .Values.cognitoUserpool.appClientId }}", "UserPoolDomain":"{{
      .Values.cognitoUserpool.domain }}"}'
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/certificate-arn: '{{ .Values.route53.subDomain.certArn
      }}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    checksum/config/cognito/parameters: {{ include (print $.Template.BasePath "/ConfigMap/istio-ingress-cognito-parameters.yaml") . | sha256sum }}
    checksum/config/ingress/parameters: {{ include (print $.Template.BasePath "/ConfigMap/istio-ingress-parameters-istio-system-ConfigMap.yaml") . | sha256sum }}  
  labels:
    kustomize.component: istio-ingress
  name: istio-ingress
  namespace: istio-system
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
        path: /*
