apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: s3-secret
  namespace: kubeflow
spec:
  parameters:
    objects: "- jmesPath:\n  - objectAlias: access\n    path: accesskey\n  - objectAlias:\
      \ secret\n    path: secretkey\n  objectName: {{ .Values.s3.secretName }}\n  objectType: secretsmanager\n"
  provider: aws
  secretObjects:
  - data:
    - key: accesskey
      objectName: access
    - key: secretkey
      objectName: secret
    secretName: mlpipeline-minio-artifact
    type: Opaque
