apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi