apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./base
  - ./cache-deployer-cert-manager

namespace: kubeflow

# Delete the cache deployer as we use the cert-manager instead 
patchesStrategicMerge:
  - ./delete-cache-deployer.yaml

# Pass proper arguments to cache-server to use cert-manager certificate
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--tls_cert_filename=tls.crt"
  target:
    kind: Deployment
    name: cache-server
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--tls_key_filename=tls.key"
  target:
    kind: Deployment
    name: cache-server

# Use the internal kfp-cache-server image built to support cert-manager
images:
  - name: gcr.io/ml-pipeline/cache-server
    newName: public.ecr.aws/h2m4d6t3/kfp-cache-server
    newTag: 1.8.1
