apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../rds-s3/base
resources:
  # Configured for AWS RDS

  # AWS Secret Manager
  - ../../../awsconfigs/common/aws-secrets-manager/rds
  # Kubeflow Pipelines
  - ../../../awsconfigs/apps/pipeline/rds
  # Katib
  - ../../../awsconfigs/apps/katib-external-db-with-kubeflow
