apiVersion: v1
data:
  config: |
    {
    artifactRepository:
    {
        s3: {
            bucket: {{ .Values.s3.bucketName }},
            keyPrefix: artifacts,
            endpoint: {{ .Values.s3.minioServiceHost }},
            insecure: false,
            useSDKCreds: true,
            keyFormat: "artifacts/{{`{{workflow.name}}`}}/{{`{{workflow.creationTimestamp.Y}}`}}/{{`{{workflow.creationTimestamp.m}}`}}/{{`{{workflow.creationTimestamp.d}}`}}/{{`{{pod.name}}`}}"
        },
        archiveLogs: true,
        containerRuntimeExecutor: emissary
    }
    }
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller-configmap
  namespace: kubeflow