apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Kubeflow namespace
- ../../../common/kubeflow-namespace/base | kubectl apply -f -
# Kubeflow Roles
- ../../../common/kubeflow-roles/base | kubectl apply -f -
# Cert-Manager
- ../../../common/cert-manager/cert-manager/base
- ../../../common/cert-manager/kubeflow-issuer/base
# Istio
- ../../../common/istio-1-9/istio-crds/base
- ../../../common/istio-1-9/istio-namespace/base
- ../../../common/istio-1-9/istio-install/base
# KNative
- ../../../common/knative/knative-serving/base | kubectl apply -f -
- ../../../common/knative/knative-eventing/base | kubectl apply -f -
- ../../../common/istio-1-9/cluster-local-gateway/base | kubectl apply -f -
# Kubeflow Istio Resources
- ../../../common/istio-1-9/kubeflow-istio-resources/base | kubectl apply -f -

# KFServing
- ../../../apps/kfserving/upstream/overlays/kubeflow | kubectl apply -f -
# Central Dashboard
- ../../../apps/centraldashboard/upstream/overlays/istio | kubectl apply -f -
# Notebooks
- ../../../apps/jupyter/notebook-controller/upstream/overlays/kubeflow | kubectl apply -f -
- ../../../apps/jupyter/jupyter-web-app/upstream/overlays/istio | kubectl apply -f -
# Admission Webhook
- ../../../apps/admission-webhook/upstream/overlays/cert-manager | kubectl apply -f -
# Profiles + KFAM
- ../../../apps/profiles/upstream/overlays/kubeflow | kubectl apply -f -
# Volumes Web App
- ../../../apps/volumes-web-app/upstream/overlays/istio | kubectl apply -f -
# Tensorboard
- ../../../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio | kubectl apply -f -
- ../../../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow | kubectl apply -f -
# TFJob Operator
- ../../../apps/tf-training/upstream/overlays/kubeflow | kubectl apply -f -
# Pytorch Operator
- ../../../apps/pytorch-job/upstream/overlays/kubeflow | kubectl apply -f -
# MPI Operator
- ../../../apps/mpi-job/upstream/overlays/kubeflow | kubectl apply -f -
# MXNet Operator
- ../../../apps/mxnet-job/upstream/overlays/kubeflow | kubectl apply -f -
# XGBoost Operator
- ../../../apps/xgboost-job/upstream/overlays/kubeflow | kubectl apply -f -

# Configured for AWS Cognito

# Ingress
- ../../../distributions/aws/istio-ingress/overlays/cognito | kubectl apply -f -
# ALB controller
- ../../../distributions/aws/aws-alb-ingress-controller/base | kubectl apply -f -
# Envoy filter
- ../../../distributions/aws/aws-istio-envoy-filter/base | kubectl apply -f -

# Configured for AWS RDS and AWS S3

# Kubeflow Pipelines
- ../../../apps/pipeline/upstream/env/aws
# Katib
- ../../../apps/katib/upstream/installs/katib-external-db-with-kubeflow