baseURL = "/"
title = "Kubeflow on AWS [STAGING]"
description = "Kubeflow makes deployment of ML Workflows on Kubernetes straightforward and automated"

enableRobotsTXT = true

theme = ["docsy"]

###############################################################################
# Docsy
###############################################################################
enableGitInfo = true

# language settings
contentDir = "content/en"
defaultContentLanguage = "en"
# tell Hugo not to include the /en/ element in the URL path for English docs
defaultContentLanguageInSubdir = false
# useful when translating
enableMissingTranslationPlaceholders = true
# disable taxonomies
disableKinds = ["taxonomy", "taxonomyTerm"]

###############################################################################
# Hugo - Top-level navigation (horizontal)
###############################################################################
[menu]
  [[menu.main]]
    name = "Documentation"
    weight = -101
    pre = "<i class='fas fa-book pr-2'></i>"
    url = "/docs/"
  [[menu.main]]
    name = "GitHub"
    weight = -99
    pre = "<i class='fab fa-github pr-2'></i>"
    url = "https://github.com/awslabs/kubeflow-manifests"

###############################################################################
# Docsy - Goldmark markdown parser
###############################################################################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    guessSyntax = "true"

###############################################################################
# Docsy - Image processing configuration
###############################################################################
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

###############################################################################
# Docsy - Services configuration
###############################################################################
[services]
  [services.googleAnalytics]
  id = "UA-135379910-1"

###############################################################################
# Docsy - Language configuration
###############################################################################
[languages]
  [languages.en]
    title = "Kubeflow on AWS"
    description = "Kubeflow makes deployment of ML Workflows on Kubernetes straightforward and automated"
    languageName ="English"
    # weight used for sorting in the language menu
    weight = 1

###############################################################################
# Docsy - Site Parameters
###############################################################################
[params]
  github_repo = "https://github.com/awslabs/kubeflow-manifests/docs"
  github_project_repo = "https://github.com/awslabs/kubeflow-manifests"

  RSSLink = "/index.xml"
  author = "kubeflow.org" # add your company name
  github = "AWS Labs" # add your github profile name
  twitter = "kubeflow" # add your twitter profile

  copyright = "The Kubeflow on AWS Authors."
  # privacy_policy = "https://aws.amazon.com/privacy/"

  # Google Custom Search Engine ID.
  gcs_engine_id = "007239566369470735695:624rglujm-w"

  # Text label for the version menu in the top bar of the website.
  version_menu = "Releases"

  # The major.minor version tag for the version of the docs represented in this
  # branch of the repository. Used in the "version-banner" partial to display a
  # version number for this doc set.
  version = "main"

  # Flag used in the "version-banner" partial to decide whether to display a
  # banner on every page indicating that this is an archived version of the docs.
  archived_version = false

  # A link to latest version of the docs. Used in the "version-banner" partial to
  # point people to the main doc site.
  url_latest_version = "/docs"

  # A variable used in various docs to determine URLs for config files etc.
  # To find occurrences, search the repo for 'params "githubbranch"'.
  githubbranch = "main"

  # These entries appear in the drop-down menu at the top of the website.
  [[params.versions]]
    version = "1.4"
    githubbranch = "main"
    url = "https://awslabs.github.io/kubeflow-manifests/docs"

  # User interface configuration
  [params.ui]
    # Enable the logo
    navbar_logo = false
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact = true
    # Enable the search box in the side bar.
    sidebar_search_disable = false
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable = false
    # Show expand/collapse icon for sidebar sections
    sidebar_menu_foldable = true
    # Disable about button in footer
    footer_about_disable = true

      # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
      # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
      # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
      # add "hide_feedback: true" to the page's front matter.
      [params.ui.feedback]
        enable = true
        # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
        yes = 'Glad to hear it! Please <a href="https://github.com/awslabs/kubeflow-manifests/issues/new?assignees=&labels=documentation&template=documentation-request.md&title=">tell us how we can improve</a>.'
        no = 'Sorry to hear that. Please <a href="https://github.com/awslabs/kubeflow-manifests/issues/new?assignees=&labels=documentation&template=documentation-request.md&title=">tell us how we can improve</a>.'