apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: '1.0'
  name: kserve-controller-manager-service
  namespace: kserve
spec:
  ports:
  - port: 443
  selector:
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: '1.0'
