apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.2.5
    istio-injection: enabled
    serving.knative.dev/release: v1.2.5
  name: knative-serving
