name: github pages

on:
  push:
    branches:
      - kf-aws-website  # Set a branch to trigger deployment
    paths:
#      - website/** # Set a directory to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/kf-aws-website'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: website-publish-test # Set a publishing branch
        #  publish_dir: ./public
